In [1]:
import pandas as pd
import numpy as np

In [4]:
train=pd.read_csv("train.csv")
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
train.shape

(891, 12)

In [6]:
train.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [11]:
train["Survived"].dtype

dtype('int64')

In [7]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [16]:
train = train.drop(['PassengerId', 'Pclass','Name',  
                    'SibSp', 'Parch', 'Ticket', 'Fare', 
                    'Cabin', 'Embarked'], axis=1)

In [17]:
train.shape

(891, 3)

In [18]:
train.head()

   Survived  Sex   Age
0         0    1  22.0
1         1    0  38.0
2         1    0  26.0
3         1    0  35.0
4         0    1  35.0

In [19]:
train['Sex'] = train['Sex'].replace({'male': 1, 'female': 0})

In [20]:
train.head()

   Survived  Sex   Age
0         0    1  22.0
1         1    0  38.0
2         1    0  26.0
3         1    0  35.0
4         0    1  35.0

In [21]:
train.isnull().sum()

Survived      0
Sex           0
Age         177
dtype: int64

In [22]:
print(train['Age'].mean())

29.69911764705882

In [23]:
train['Age'] = train['Age'].fillna(train['Age'].mean())

In [24]:
train.isnull().sum()

Survived    0
Sex         0
Age         0
dtype: int64

In [25]:
X = train.drop('Survived', axis=1)
y = train['Survived']

In [26]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42)

In [29]:
model = SVC()
model.fit(X, y)

SVC()

In [30]:
y_pred = model.predict(X_test)

/opt/anaconda3/envs/t_env/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [31]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.4134078212290503

In [32]:
model2=DecisionTreeClassifier()
model2.fit(X,y)

DecisionTreeClassifier()

In [33]:
y_pred2=model2.predict(X_test)

/opt/anaconda3/envs/t_env/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [34]:
accuracy = accuracy_score(y_test, y_pred2)
print("Accuracy:", accuracy)

Accuracy: 0.4134078212290503

In [35]:
model3=RandomForestClassifier()
model3.fit(X,y)

RandomForestClassifier()

In [36]:
y_pred3=model3.predict(X_test)

/opt/anaconda3/envs/t_env/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [37]:
accuracy = accuracy_score(y_test, y_pred3)
print("Accuracy:", accuracy)

Accuracy: 0.41899441340782123

In [38]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
clf.fit(X, y)

/opt/anaconda3/envs/t_env/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py:713: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

SGDClassifier(max_iter=5)

In [39]:
g_pred=clf.predict(X_test)

/opt/anaconda3/envs/t_env/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(

In [40]:
accuracy = accuracy_score(y_test, g_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7821229050279329

In [42]:
%pip install xgboost

Requirement already satisfied: xgboost in /opt/anaconda3/envs/t_env/lib/python3.8/site-packages (2.1.4)
Requirement already satisfied: numpy in /opt/anaconda3/envs/t_env/lib/python3.8/site-packages (from xgboost) (1.24.4)
Requirement already satisfied: scipy in /opt/anaconda3/envs/t_env/lib/python3.8/site-packages (from xgboost) (1.10.1)
Note: you may need to restart the kernel to use updated packages.

In [46]:
import pandas as pd

new_passenger = pd.DataFrame({
    
    'Sex': [1],     # must match encoding (e.g., male=1, female=0)
    'Age': [22]
    
})

In [47]:
prediction = clf.predict(new_passenger)
print(prediction)

[1]